// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_kill_10_enemies = "CgkImt_Vrr0QEAIQCA"; // <GPGSID>
        public const string achievement_unlock_gold_armor = "CgkImt_Vrr0QEAIQBw"; // <GPGSID>
        public const string achievement_collect_500_laddus = "CgkImt_Vrr0QEAIQAw"; // <GPGSID>
        public const string achievement_unlock_all_maps = "CgkImt_Vrr0QEAIQBQ"; // <GPGSID>
        public const string achievement_collect_100_laddus = "CgkImt_Vrr0QEAIQAg"; // <GPGSID>
        public const string leaderboard_hanumanrun_leaderboard = "CgkImt_Vrr0QEAIQAQ"; // <GPGSID>
        public const string achievement_kill_50_enemies = "CgkImt_Vrr0QEAIQCQ"; // <GPGSID>
        public const string achievement_kill_100_enemies = "CgkImt_Vrr0QEAIQCg"; // <GPGSID>
        public const string achievement_collect_1000_laddus = "CgkImt_Vrr0QEAIQBA"; // <GPGSID>
        public const string achievement_unlock_silver_armor = "CgkImt_Vrr0QEAIQBg"; // <GPGSID>

}

